apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: streamlit
  name: streamlit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: streamlit
    spec:
      containers:
      - image: codex0915/house-price-predict-streamlit:dev
        name: house-price-predict-streamlit
        ports:
        - containerPort: 8501
        resources: {}
status: {}